FROM quay.io/almalinuxorg/almalinux-bootc:10-kitten

LABEL containers.bootc 1

WORKDIR /workdir

COPY 10/system_root ./system_root
COPY 10/*.sh .
COPY 10/*.yaml .

RUN <<EOF bash
    set -xeuo pipefail

    dnf install -y ansible-core
    ansible-playbook playbook.yaml
EOF

RUN <<EOF bash
    set -xeuo pipefail

    rm -rdf /workdir
    dnf remove -y ansible-core
    bootc container lint
EOF
