FROM quay.io/almalinuxorg/almalinux-bootc:10-kitten

LABEL containers.bootc 1

RUN dnf update -y
RUN dnf install -y ansible-core

WORKDIR /workdir

COPY 10/system_root ./system_root
COPY 10/*.sh .
COPY 10/*.yaml .
RUN cp -rf /workdir/system_root/* /

RUN ansible-playbook playbook.yaml

RUN dnf remove -y ansible-core && dnf clean all
RUN rm -rdf /workdir

RUN bootc container lint
